webgallery/gallery/urls.py
from django.urls import path
from gallery import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'gallery'
urlpatterns = [
    path('', views.home, name="home"),
    path('login/', views.user_login, name="login"),
    path('register/', views.register, name="register"),
    path('logout/', views.user_logout, name="logout"),
    path('images/', views.home, name="images"),
    path('images/<int:post_id>/', views.detail, name="detail"),
    path('images/<int:post_id>/delete/', views.delete_post, name='delete'),
    path('images/<int:post_id>/edit/', views.edit_post, name='edit'),
    path('gallery/', views.gallery, name="gallery"),
    path('gallery_column/', views.gallery_column, name="gallery_column"),
    path('gallery_full', views.gallery_full, name="gallery_full"),
    path('search', views.search, name="search"),
    path('add_img/', views.createpost, name="add_img"),
    path('edit_profile/', views.edit_profile, name="edit_profile"),
    path('password/', views.change_password, name="change_password"),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

webgallery/webgallery/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('gallery.urls')),
]

webgallery/gallery/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime
from os import path


def prof_dir(instance, filename):
    return "%s/%s" % (instance.user, filename)


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post_img = models.ImageField(upload_to=prof_dir)
    title = models.CharField(max_length=50)
    create_time = models.DateTimeField(default=datetime.now)

    def __str__(self):
        return self.title

    def file_name(self):
        return path.basename(self.post_img.name)

    def file_extension(self):
        name, extension = path.splitext(self.post_img.name)
        return extension

    def file_size(self):
        return f"{self.post_img.size / 1000000} MB"


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_pic = models.ImageField(
        upload_to=prof_dir, default='default.jpg', blank=True)

    def __str__(self):
        return self.user.username

webgallery/gallery/forms.py
from django import forms
from gallery.models import UserProfile, Post
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from crispy_forms.helper import FormHelper, Layout


class UserForm(UserCreationForm):

    class Meta:
        model = User
        fields = (
            'username',
            'email',
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.wrapper_class = 'row'
        self.helper.label_class = 'col-lg-3'
        self.helper.field_class = 'col-lg-9'


class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput())


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('profile_pic',)


class UserPostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'post_img')


class EditProfileForm(UserChangeForm):
    class Meta:
        model = User
        password = forms.CharField()
        fields = (
            'email',
            'first_name',
            'username',
            'password',
        )


class EditPostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = (
            'title',
        )

webgallery/gallery/views.py
from django.shortcuts import render, redirect
from gallery.forms import (
    UserForm,
    UserLoginForm,
    UserProfileForm,
    UserPostForm,
    EditProfileForm,
    EditPostForm,
)
from gallery.models import Post, UserProfile
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm, UserCreationForm
from django.contrib.auth import update_session_auth_hash
from django.db.models import Q


def get_post(user, id):
    return Post.objects.filter(user=user).get(id=id)


def get_all_posts(user):
    return Post.objects.filter(user=user).all()


@login_required
def home(request):
    queryset = get_all_posts(request.user)
    context = {'page_title': 'Your photos', 'queryset': queryset}
    return render(request, 'pages/images.html', context)


@login_required
def gallery(request):
    queryset = get_all_posts(request.user)
    context = {'page_title': 'Gallery', 'queryset': queryset}
    return render(request, 'pages/gallery.html', context)

@login_required
def gallery_column(request):
    queryset = get_all_posts(request.user)
    context = {'page_title': 'Gallery', 'queryset': queryset}
    return render(request, 'pages/gallery_column.html', context)


@login_required
def gallery_full(request):
    queryset = get_all_posts(request.user)
    context = {'page_title': 'Full screen', 'queryset': queryset}
    return render(request, 'pages/gallery_full.html', context)


@login_required
def edit_profile(request):
    if request.method == 'POST':
        edit_form = EditProfileForm(request.POST, instance=request.user)
        profile = request.user.userprofile
        profile_form = UserProfileForm(
            request.POST, request.FILES, instance=profile)
        if edit_form.is_valid() and profile_form.is_valid():
            edit_form.save()
            profile_form.save()
            return redirect('gallery:edit_profile')
    else:
        edit_form = EditProfileForm(instance=request.user)
        profile_form = UserProfileForm(request.POST)
    context = {'edit_form': edit_form, 'profile_form': profile_form}
    return render(request, 'pages/edit_profile.html', context)


@login_required
def change_password(request):
    if request.method == 'POST':
        pass_form = PasswordChangeForm(data=request.POST, user=request.user)
        if pass_form.is_valid():
            pass_form.save()
            update_session_auth_hash(request, pass_form.user)
            return redirect('gallery:edit_profile')
    else:
        pass_form = PasswordChangeForm(user=request.user)
    context = {'pass_form': pass_form}
    return render(request, 'pages/edit_password.html', context)


@login_required
def delete_post(request, post_id=None):
    obj = get_post(request.user, post_id)
    obj.delete()
    return redirect('gallery:home')


@login_required
def edit_post(request, post_id=None):
    obj = get_post(request.user, post_id)
    form = EditPostForm(request.POST or None, instance=obj)
    if form.is_valid():
        form.save()
        return redirect('gallery:detail', post_id=post_id)
    template_name = 'pages/edit_post.html'
    context = {'page_title': 'Edit post', 'post_form': form}
    return render(request, template_name, context)


@login_required
def detail(request, post_id):
    obj = get_post(request.user, post_id)
    context = {'page_title': 'test', 'object': obj}
    return render(request, 'pages/detail.html', context)


@login_required
def createpost(request):
    if request.method == 'POST':
        post_form = UserPostForm(request.POST, request.FILES)
        if post_form.is_valid():
            obj = post_form.save(commit=False)
            obj.user = request.user
            obj.save()
            return redirect('gallery:home')
    else:
        post_form = UserPostForm()
    context = {'page_title': 'Add image', 'post_form': post_form}
    return render(request, 'pages/add_img.html', context)


@login_required
def search(request):
    query = request.GET.get('q')
    if query:
        result = Post.objects.filter(Q(title__icontains=query) | Q(post_img__icontains=query), user=request.user)
        template = 'pages/images.html'
        context = {"queryset": result}
        return render(request, template, context)
    return redirect('gallery:home')
    


def user_login(request):
    if request.user.is_authenticated:
        return redirect('gallery:home')
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                # Here redirect to user page with home.html
                return redirect('gallery:home')
            else:
                return HttpResponse("Your account was inactive")
        else:
            return HttpResponse("Invalid login credentials")
    else:
        login_form = UserLoginForm()
        context = {'page_title': 'Login', 'login_form': login_form}
        return render(request, 'pages/login.html', context)


def register(request):
    if request.user.is_authenticated:
        return redirect('gallery:home')
    registered = False
    if request.method == 'POST':
        user_form = UserForm(request.POST)
        profile_form = UserProfileForm(request.POST, request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            profile.save()
            registered = True
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    return render(request, 'pages/register.html', {
        'user_form': user_form,
        'profile_form': profile_form,
        'registered': registered,
        'page_title': 'Register'
    })


@login_required
def user_logout(request):
    logout(request)
    return redirect('gallery:login')

webgallery/gallery/templates/pages/add_img.html
{% extends 'card.html' %}
{% load crispy_forms_tags %}

{% block card_content %}

<h1>Upload image</h1>
<form method="POST" action="{% url 'gallery:add_img' %}" enctype="multipart/form-data">
    {% csrf_token %}
    {{ post_form|crispy }}
    <input type="submit" name="" value="Save">
</form>

{% endblock %}

webgallery/gallery/templates/pages/detail.html
{% extends 'base.html'%}

{% block content %}

{% if user.is_authenticated %}
<div class="row">
    <div class="col-sm-12 text-center">
        <h2 class="img-title">{{ object.title }}</h2>
    </div>
</div>
<div class="row">
    <div class="col-sm-12 text-center">
        <img class="detail-img img-fluid" src="{{ object.post_img.url }}" alt="">
    </div>
</div>
<div class="row mt-2">
    <div class="col"></div>
    <div class="mt-3 col-sm-3 text-center">
        <a class="btn btn-outline-danger" href="{% url 'gallery:delete' object.id%}">Delete</a>
    </div>
    <div class="mt-3 col-sm-3 text-center">
        <a class="btn btn-outline-primary" href="{% url 'gallery:edit' object.id%}">Edit</a>
    </div>
    <div class="col"></div>
</div>
{% else %}
<p>Please <a href="{% url 'gallery:login' %}">login</a> first</p>
{% endif %}

{% endblock %}

webgallery/gallery/templates/pages/edit_password.html
{% extends 'base.html'%}
{% load crispy_forms_tags %}

{% block content %}

{% if user.is_authenticated %}
<div class="row">
    <div class="col"></div>
    <div class="col-sm-6">
        <form method="post">
            {% csrf_token %}
            {{ pass_form|crispy }}
            <input type="submit" name="" value="Change">
        </form>
    </div>
    <div class="col"></div>
</div>

{% else %}
<p>Please <a href="{% url 'gallery:login' %}">login</a> first</p>
{% endif %}

{% endblock %}

webgallery/gallery/templates/pages/edit_post.html
{% extends 'card.html' %}
{% load crispy_forms_tags %}

{% block card_content %}

<h1>Edit post</h1>
<form method="POST" action="">
    {% csrf_token %}
    {{ post_form|crispy }}
    <input type="submit" name="" value="Post">
</form>

{% endblock %}

webgallery/gallery/templates/pages/edit_profile.html
{% extends 'base.html'%}
{% load crispy_forms_tags %}

{% block content %}

{% if user.is_authenticated %}

<div class="row">
    <div class="col"></div>
    <div class="col-sm-6">
        <img class="profile-img profile-img-large mb-3" src="{{ request.user.userprofile.profile_pic.url }}" alt="">
        <form method="post" action="" enctype="multipart/form-data">
            {% csrf_token %}
            {{ profile_form|crispy }}
            {% for field in edit_form %}
                {% if field.name != 'password' %}
                    {{ field|as_crispy_field }}
                {% endif %}
            {% endfor %}
            {{ edit_form.password }}
            <p>{{ edit_form.password.help_text|safe }}</p>
            <input type="submit" name="" value="Change">
        </form>
    </div>
    <div class="col"></div>

</div>

{% else %}
<p>Please <a href="{% url 'gallery:login' %}">login</a> first</p>
{% endif %}

{% endblock %}

webgallery/gallery/templates/pages/gallery.html
{% extends 'base.html'%}

{% block content %}

{% if user.is_authenticated %}
<div class="justified-gallery">
    {% for image in queryset %}
    <a href="{{ image.post_img.url }}">
        <img src="{{ image.post_img.url }}">
    </a>
    {% endfor %}
</div>

{% else %}
<p>Please <a href="{% url 'gallery:login' %}">login</a> first</p>
{% endif %}

{% endblock %}

webgallery/gallery/templates/pages/gallery_column.html
{% extends 'master.html' %}

{% block master_content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-3 background"></div>
        <main class="col-lg-6">
            <div class="text-center">
                {% for image in queryset %}
                <a href="{{ image.post_img.url }}" class="d-block mb-5 h-100">
                    <img class="img-fluid border" src="{{ image.post_img.url }}" alt="">
                </a>
                {% endfor %}
            </div>
        </main>
        <div class="col-lg-3 background"></div>
    </div>
</div>
{% endblock %}

webgallery/gallery/templates/pages/gallery_full.html
{% load static %}

<!doctype html>
<html lang="en">

<head>
	<!-- Required meta tags -->
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/lightgallery/1.6.12/css/lightgallery.min.css" />
	<link rel="stylesheet"
		href="https://cdnjs.cloudflare.com/ajax/libs/justifiedGallery/3.7.0/css/justifiedGallery.min.css" />
	<link rel="stylesheet" href="{% static 'css/style.css' %}" />

	<title>{{ page_title }}</title>
</head>

<body>
	<div class="justified-gallery">
		{% for image in queryset %}
		<a href="{{ image.post_img.url }}">
			<img src="{{ image.post_img.url }}">
		</a>
		{% endfor %}
	</div>
	<!-- Optional JavaScript -->
	<!-- jQuery first, then Popper.js, then Bootstrap JS -->
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
		integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
		crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-mousewheel/3.1.13/jquery.mousewheel.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/lightgallery/1.6.12/js/lightgallery-all.min.js"></script>
	<script
		src="https://cdnjs.cloudflare.com/ajax/libs/justifiedGallery/3.7.0/js/jquery.justifiedGallery.min.js"></script>
	<script src="{% static 'js/script.js' %}"></script>
</body>

</html>

webgallery/gallery/templates/pages/home.html
{% extends 'base.html'%}

{% block content %}

{% if user.is_authenticated %}
<div class="justified-gallery">
    {% for queryset in querysets %}
    <a href="{{ queryset.post_img.url }}">
        <img src="{{ queryset.post_img.url }}">
    </a>
    {% endfor %}
</div>

{% else %}
<p>Please <a href="{% url 'gallery:login' %}">login</a> first</p>
{% endif %}

{% endblock %}

webgallery/gallery/templates/pages/images.html
{% extends 'base.html' %}

{% block content %}
<div class="table-responsive">
    <table class="table table-sm table-borderless text-center">
        <thead>
            <tr>
                <th class="pr-5">Thumbnail</th>
                <th class="pr-5">File name</th>
                <th class="pr-5">Date uploaded</th>
                <th class="pr-5">Type</th>
                <th class="pr-5">Size</th>
            </tr>
        </thead>
        <tbody>
            {% for image in queryset %}
            <tr>
                <td class="pr-5">
                    <a href="{% url 'gallery:detail' post_id=image.id %}" >
                        <img class="img-fluid" src="{{ image.post_img.url }}" alt="">
                    </a>
                </td>
                <td class="pr-5"><a href="{% url 'gallery:detail' post_id=image.id %}">{{ image.file_name }}</a></td>
                <td class="pr-5">{{ image.create_time }} UTC</td>
                <td class="pr-5">{{ image.file_extension }}</td>
                <td class="pr-5">{{ image.file_size }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}

webgallery/gallery/templates/pages/login.html
{% extends 'card.html' %}
{% load crispy_forms_tags %}

{% block card_content %}

<h2>Login</h2>

<form method="POST" action="{% url 'gallery:login' %}">
    {% csrf_token %}
    {{ login_form|crispy }}
    <input type="submit" name="" value="Log in">
</form>
<br>
<p>Not registered? Click <a href="{% url 'gallery:register' %}">here</a> to register.</p>

{% endblock %}

webgallery/gallery/templates/pages/main.html
{% extends 'base.html'%}

{% block content %}
<h1>Web Gallery</h1>
{% endblock %}

webgallery/gallery/templates/pages/register.html
{% extends 'card.html' %}
{% load crispy_forms_tags %}

{% block card_content %}

{% if registered %}
<h2>Thank you for registering!</h2>
<a href="{% url 'gallery:login' %}">Log in to your account</a>

{% else %}
<h2>Register</h2>
<form method="POST" action="" enctype="multipart/form-data">
    {% csrf_token %}
    {% crispy user_form %}
    {{ profile_form.as_p }}
    <input type="submit" name="" value="Register">
</form>
<br>
<p>If you already have an account, <a href="/login">log in </a> instead.</p>
{% endif %}

{% endblock %}