webgallery/gallery/urls.py
from django.urls import path
from gallery import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'gallery'
urlpatterns = [
    path('', views.home, name="home"),
    path('login/', views.user_login, name="login"),
    path('register/', views.register, name="register"),
    path('logout/', views.user_logout, name="logout"),
    path('images/', views.home, name="images"),
    path('images/<int:post_id>/', views.detail, name="detail"),
    path('images/<int:post_id>/delete/', views.delete_post, name='delete'),
    path('images/<int:post_id>/edit/', views.edit_post, name='edit'),
    path('gallery/', views.gallery, name="gallery"),
    path('gallery_column/', views.gallery_column, name="gallery_column"),
    path('gallery_full', views.gallery_full, name="gallery_full"),
    path('search', views.search, name="search"),
    path('add_img/', views.createpost, name="add_img"),
    path('edit_profile/', views.edit_profile, name="edit_profile"),
    path('password/', views.change_password, name="change_password"),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

webgallery/webgallery/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('gallery.urls')),
]

webgallery/gallery/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime
from os import path


def prof_dir(instance, filename):
    return "%s/%s" % (instance.user, filename)


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post_img = models.ImageField(upload_to=prof_dir)
    title = models.CharField(max_length=50)
    create_time = models.DateTimeField(default=datetime.now)

    def __str__(self):
        return self.title

    def file_name(self):
        return path.basename(self.post_img.name)

    def file_extension(self):
        name, extension = path.splitext(self.post_img.name)
        return extension

    def file_size(self):
        return f"{self.post_img.size / 1000000} MB"


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_pic = models.ImageField(
        upload_to=prof_dir, default='default.jpg', blank=True)

    def __str__(self):
        return self.user.username

webgallery/gallery/forms.py
from django import forms
from gallery.models import UserProfile, Post
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from crispy_forms.helper import FormHelper, Layout


class UserForm(UserCreationForm):

    class Meta:
        model = User
        fields = (
            'username',
            'email',
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.wrapper_class = 'row'
        self.helper.label_class = 'col-lg-3'
        self.helper.field_class = 'col-lg-9'


class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput())


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('profile_pic',)


class UserPostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'post_img')


class EditProfileForm(UserChangeForm):
    class Meta:
        model = User
        password = forms.CharField()
        fields = (
            'email',
            'first_name',
            'username',
            'password',
        )


class EditPostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = (
            'title',
        )

webgallery/gallery/views.py
from django.shortcuts import render, redirect
from gallery.forms import (
    UserForm,
    UserLoginForm,
    UserProfileForm,
    UserPostForm,
    EditProfileForm,
    EditPostForm,
)
from gallery.models import Post, UserProfile
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm, UserCreationForm
from django.contrib.auth import update_session_auth_hash
from django.db.models import Q


def get_post(user, id):
    return Post.objects.filter(user=user).get(id=id)


def get_all_posts(user):
    return Post.objects.filter(user=user).all()


@login_required
def home(request):
    queryset = get_all_posts(request.user)
    context = {'page_title': 'Your photos', 'queryset': queryset}
    return render(request, 'pages/images.html', context)


@login_required
def gallery(request):
    queryset = get_all_posts(request.user)
    context = {'page_title': 'Gallery', 'queryset': queryset}
    return render(request, 'pages/gallery.html', context)

@login_required
def gallery_column(request):
    queryset = get_all_posts(request.user)
    context = {'page_title': 'Gallery', 'queryset': queryset}
    return render(request, 'pages/gallery_column.html', context)


@login_required
def gallery_full(request):
    queryset = get_all_posts(request.user)
    context = {'page_title': 'Full screen', 'queryset': queryset}
    return render(request, 'pages/gallery_full.html', context)


@login_required
def edit_profile(request):
    if request.method == 'POST':
        edit_form = EditProfileForm(request.POST, instance=request.user)
        profile = request.user.userprofile
        profile_form = UserProfileForm(
            request.POST, request.FILES, instance=profile)
        if edit_form.is_valid() and profile_form.is_valid():
            edit_form.save()
            profile_form.save()
            return redirect('gallery:edit_profile')
    else:
        edit_form = EditProfileForm(instance=request.user)
        profile_form = UserProfileForm(request.POST)
    context = {'edit_form': edit_form, 'profile_form': profile_form}
    return render(request, 'pages/edit_profile.html', context)


@login_required
def change_password(request):
    if request.method == 'POST':
        pass_form = PasswordChangeForm(data=request.POST, user=request.user)
        if pass_form.is_valid():
            pass_form.save()
            update_session_auth_hash(request, pass_form.user)
            return redirect('gallery:edit_profile')
    else:
        pass_form = PasswordChangeForm(user=request.user)
    context = {'pass_form': pass_form}
    return render(request, 'pages/edit_password.html', context)


@login_required
def delete_post(request, post_id=None):
    obj = get_post(request.user, post_id)
    obj.delete()
    return redirect('gallery:home')


@login_required
def edit_post(request, post_id=None):
    obj = get_post(request.user, post_id)
    form = EditPostForm(request.POST or None, instance=obj)
    if form.is_valid():
        form.save()
        return redirect('gallery:detail', post_id=post_id)
    template_name = 'pages/edit_post.html'
    context = {'page_title': 'Edit post', 'post_form': form}
    return render(request, template_name, context)


@login_required
def detail(request, post_id):
    obj = get_post(request.user, post_id)
    context = {'page_title': 'test', 'object': obj}
    return render(request, 'pages/detail.html', context)


@login_required
def createpost(request):
    if request.method == 'POST':
        post_form = UserPostForm(request.POST, request.FILES)
        if post_form.is_valid():
            obj = post_form.save(commit=False)
            obj.user = request.user
            obj.save()
            return redirect('gallery:home')
    else:
        post_form = UserPostForm()
    context = {'page_title': 'Add image', 'post_form': post_form}
    return render(request, 'pages/add_img.html', context)


@login_required
def search(request):
    query = request.GET.get('q')
    if query:
        result = Post.objects.filter(Q(title__icontains=query) | Q(post_img__icontains=query), user=request.user)
        template = 'pages/images.html'
        context = {"queryset": result}
        return render(request, template, context)
    return redirect('gallery:home')
    


def user_login(request):
    if request.user.is_authenticated:
        return redirect('gallery:home')
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                # Here redirect to user page with home.html
                return redirect('gallery:home')
            else:
                return HttpResponse("Your account was inactive")
        else:
            return HttpResponse("Invalid login credentials")
    else:
        login_form = UserLoginForm()
        context = {'page_title': 'Login', 'login_form': login_form}
        return render(request, 'pages/login.html', context)


def register(request):
    if request.user.is_authenticated:
        return redirect('gallery:home')
    registered = False
    if request.method == 'POST':
        user_form = UserForm(request.POST)
        profile_form = UserProfileForm(request.POST, request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            profile.save()
            registered = True
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    return render(request, 'pages/register.html', {
        'user_form': user_form,
        'profile_form': profile_form,
        'registered': registered,
        'page_title': 'Register'
    })


@login_required
def user_logout(request):
    logout(request)
    return redirect('gallery:login')

webgallery/gallery/templates/partials/_footer.html
<footer class="footer">
    <div class="container text-center">
        <span class="text-muted">© 2020 WebGallery</span>
    </div>
</footer>

webgallery/gallery/templates/partials/_header.html
{% load static %}

{% if user.is_authenticated %}
    {% url 'gallery:home' as home_url %}
    {% url 'gallery:gallery' as gallery_url %}
    {% url 'gallery:gallery_column' as gallery_column_url %}
    <nav class="navbar navbar-light bg-light d-block d-md-flex navbar-expand">
        <a class="navbar-brand" href="{% url 'gallery:home' %}">
            <img src="{% static 'images/logo.png' %}">
        </a>
        <form class="form-inline my-2 ml-auto" action="{% url 'gallery:search' %}">
            <input class="form-control mr-sm-2" type="search" name="q" placeholder="Search" aria-label="Search" value="{{ request.GET.q }}">
            <button class="search btn btn-outline-success mt-2 my-sm-0 mr-2" type="submit">Search</button>
        </form>
        <div class="dropdown">
            <button class="btn dropdown-toggle text-dark" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><img class="profile-img" src="{{ request.user.userprofile.profile_pic.url }}" alt=""></button>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
                <a class="dropdown-item" href="{% url 'gallery:logout' %}">Log out <i class="material-icons md-18 align-middle text-danger">exit_to_app</i></a>
                <a class="dropdown-item" href="{% url 'gallery:edit_profile' %}">Profile</a>

            </div>
        </div>
    </nav>
    <div class="toolbar bg-dark sticky-top">
        <div class="container-fluid">
            <a href="{{ home_url }}" class="float-left"><i class="material-icons md-light{% if request.get_full_path != home_url %} md-inactive{% endif %} md-36" data-toggle="tooltip" data-placement="right" title="Images">list</i></a>
            <a href="{{ gallery_url }}" class="float-left"><i class="material-icons md-light{% if request.get_full_path != gallery_url %} md-inactive{% endif %} md-36" data-toggle="tooltip" data-placement="right" title="Gallery view">view_module</i></a>
            <a href="{{ gallery_column_url }}" class="float-left"><i class="material-icons md-light{% if request.get_full_path != gallery_column_url %} md-inactive{% endif %} md-36" data-toggle="tooltip" data-placement="right" title="Column view">view_stream</i></a>
            <a href="{% url 'gallery:add_img' %}"><i class="image-upload float-right material-icons md-light md-inactive md-36" data-toggle="tooltip" data-placement="left" title="Upload">add</i></a>
            
            {% if request.get_full_path == gallery_url %}<a href="{% url 'gallery:gallery_full' %}" class="float-right"><i class="material-icons md-light md-inactive md-36" data-toggle="tooltip" data-placement="left" title="Full screen">fullscreen</i></a>{% endif %}
        </div>
    </div>

{% else %}
    <nav class="navbar navbar-light bg-light d-block d-flex navbar-expand justify-content-center">
        <a class="navbar-brand-large" href="{% url 'gallery:home' %}">
            <img src="{% static 'images/logo.png' %}">
        </a>
    </nav>
    <div class="divider"></div>
{% endif %}